# Generated by Django 3.1.2 on 2020-10-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=3)),
                ('y', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Domiciliary',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
        ),
    ]
