# Generated by Django 3.1.2 on 2020-10-30 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.CharField(default='', max_length=2, primary_key=True, serialize=False)),
                ('x', models.CharField(default='', max_length=3)),
                ('y', models.CharField(default='', max_length=3)),
                ('timestamp', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
