# Generated by Django 3.1.2 on 2020-10-30 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='timestamp',
        ),
    ]
