# Generated by Django 3.1.2 on 2020-10-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coordenate',
        ),
        migrations.AddField(
            model_name='domiciliary',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='domiciliary',
            name='x',
            field=models.CharField(default=-1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domiciliary',
            name='y',
            field=models.CharField(default=-1, max_length=3),
            preserve_default=False,
        ),
    ]
