# Generated by Django 3.1.2 on 2020-10-30 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201029_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domiciliary',
            name='timestamp',
        ),
    ]
