# Generated by Django 3.1.2 on 2020-10-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_domiciliary_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domiciliary',
            name='id',
            field=models.CharField(default='', max_length=2, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='domiciliary',
            name='x',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='domiciliary',
            name='y',
            field=models.CharField(default='', max_length=3),
        ),
    ]
