# Generated by Django 3.1.2 on 2020-10-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201029_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='domiciliary',
            name='timestamp',
            field=models.DateField(default=1604018629.7359023),
        ),
    ]
